version: "3"

volumes:
  amapj_db:
  amapj_data:

services:
  amapj:
    image: mopnaej/amapj:latest
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      - JAVA_OPTS=-Duser.country=FR -Duser.language=fr
    ports:
      - "8081:8080"
    volumes:
      - amapj_db:/opt/amapj/amapj-db
      - amapj_data:/opt/amapj/data
